version: '3'
services:
  app:
    build: .
    environment:
      - HDHR_ADVERTISE_HOST=192.168.86.254
      - HDHR_ADVERTISE_PORT=5005
      - HDHR_SCHEME=http    
    ports:
      - "5005:5005"
      - "1900:1900/udp"
    volumes:
      - .:/app
    restart: unless-stopped
    privileged: true
