services:
  app:
    build: .
    environment:
      - HDHR_ADVERTISE_HOST=${HDHR_ADVERTISE_HOST}
      - HDHR_ADVERTISE_PORT=${HDHR_ADVERTISE_PORT}
      - HDHR_SCHEME=${HDHR_SCHEME}
      # SSDP disabled by default - prevents macOS Docker hang
      # Enable via web UI "Enable Discovery" button if needed
      - HDHR_DISABLE_SSDP=${HDHR_DISABLE_SSDP}
    ports:
      - "5005:5005"
      # Port 1900 not exposed - SSDP can be enabled via web UI if needed
      # Uncomment only if you want auto-discovery AND you're on Linux
      # - "1900:1900/udp"
    volumes:
      - ./m3u_files:/app/m3u_files
      - ./data:/app/data
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    dns_search: []
    extra_hosts:
      - "host.docker.internal:host-gateway"
