services:
  app:
    build: .
    environment:
      - HDHR_ADVERTISE_HOST=${HDHR_ADVERTISE_HOST}
      # Use a single port setting; advertise the same port Plex will hit on the host
      - HDHR_ADVERTISE_PORT=${APP_PORT}
      - HDHR_SCHEME=${HDHR_SCHEME}
      # Model number shown in Plex (default "HDHR3-US")
      - HDHR_MODEL=${HDHR_MODEL:-HDHR3-US}
      # Friendly name shown in Plex (default "IPTV HDHomeRun")
      - HDHR_FRIENDLY_NAME=${HDHR_FRIENDLY_NAME:-IPTV HDHomeRun}
      # Number of concurrent tuners to advertise (default 2 if not set)
      - HDHR_TUNER_COUNT=${HDHR_TUNER_COUNT:-2}
      # SSDP disabled by default - prevents macOS Docker hang
      # Enable via web UI "Enable Discovery" button if needed
      - HDHR_DISABLE_SSDP=${HDHR_DISABLE_SSDP}
    ports:
      # Host port is configurable via .env (APP_PORT). Container listens on 5005.
      - "${APP_PORT:-5005}:5005"
      # Port 1900 not exposed - SSDP can be enabled via web UI if needed
      # Uncomment only if you want auto-discovery AND you're on Linux
      # - "1900:1900/udp"
    volumes:
      - ./m3u_files:/app/m3u_files
      - ./data:/app/data
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    dns_search: []
    extra_hosts:
      - "host.docker.internal:host-gateway"
