version: '3'
services:
  app:
    build: .
    environment:
      - HDHR_ADVERTISE_HOST=192.168.86.254
      - HDHR_ADVERTISE_PORT=5005
      - HDHR_SCHEME=http
      # Add DNS configuration
      - UVICORN_DNS_RESOLVER=1.1.1.1
    ports:
      - "5005:5005"
      - "1900:1900/udp"
    volumes:
      # Only mount the data directories that need persistence
      - ./m3u_files:/app/m3u_files
      - ./data.db:/app/data.db
    restart: unless-stopped
    privileged: true
    # Add network settings
    dns:
      - 1.1.1.1  # Cloudflare DNS
      - 8.8.8.8  # Google DNS
    dns_search: []  # Disable DNS search
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Ensure host resolution works
